# Numpy Exercises

Use the following code for the questions below:

In [2]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [24]:
len(a[a < 0])

4

In [25]:
(a < 0).sum()

4

2. How many positive numbers are there?

In [26]:
len(a[a > 0])

5

In [27]:
(a > 0).sum()

5

3. How many even positive numbers are there?

In [28]:
len(a[(a > 0) & (a % 2 == 0)])

3

In [29]:
((a > 0) & (a % 2 == 0)).sum()

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [30]:
a_plus3 = a + 3

len(a_plus3[a_plus3 > 0])

10

5. If you squared each number, what would the new mean and standard deviation be?

In [34]:
a_squared = a**2

a_squared_mean = a_squared.mean()

a_squared_mean

74.0

In [36]:
a_squared_std = a_squared.std()
a_squared_std

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [40]:
a_centered = a - a.mean()
a_centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point. Recall that the z-score is given by: $z = \frac{x-\mu}{\sigma}$

In [41]:
a_z_score = a_centered / a.std()
a_z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [47]:
# setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**setup 1**
Use python's built in functionality/operators to determine the following:

8.1.1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [48]:
sum_of_a = sum(a)
sum_of_a

55

8.1.2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [49]:
min_of_a = min(a)
min_of_a

1

8.1.3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [50]:
max_of_a = max(a)
max_of_a

10

8.1.4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [54]:
mean_of_a = sum(a)/len(a)
mean_of_a

5.5

8.1.5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [56]:
product_of_a = 1

for n in a:
    product_of_a *= n

product_of_a

3628800

8.1.6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [57]:
squares_of_a = [n**2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

8.1.7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [59]:
odds_in_a = [n for n in a if n % 2 == 1]
odds_in_a

[1, 3, 5, 7, 9]

8.1.8 - Make a variable named evens_in_a. It should hold only the evens.

In [61]:
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

**setup 2**  

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [63]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

8.2.1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**  

`sum_of_b = 0
for row in b:
sum_of_b += sum(row)`

In [65]:
b = np.array(b)
b.sum()

33

8.2.2 - refactor the following to use numpy. 

```min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])```

In [66]:
min_of_b = b.min()
min_of_b

3

8.2.3 - refactor the following maximum calculation to find the answer with numpy.

```max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])```

In [69]:
max_of_b = b.max()
max_of_b

8

8.2.4 - refactor the following using numpy to find the mean of b

```mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))```

In [71]:
mean_of_b = b.mean()
mean_of_b

5.5

8.2.5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

```product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
```

In [73]:
product_of_b = b.prod()
product_of_b

20160

8.2.6 - refactor the following to use numpy to find the list of squares 

```squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
```

In [74]:
squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

8.2.7 - refactor using numpy to determine the odds_in_b  

```odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
```



In [75]:
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

8.2.8 - refactor the following to use numpy to filter only the even numbers  

```evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
```

In [76]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

8.2.9 - print out the shape of the array b.

In [79]:
print(b.shape)

(2, 3)


8.2.10 - transpose the array b.

In [80]:
print(b.T)

[[3 6]
 [4 7]
 [5 8]]


8.2.11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [81]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

8.2.12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [84]:
b.reshape(-1, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.


In [85]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


8.3.1 - Find the min, max, sum, and product of c.

In [88]:
c = np.array(c)

print(c.min(), c.max(), c.sum(), c.prod())

1 9 45 362880


8.3.2 - Determine the standard deviation of c.

In [89]:
c.std()

2.581988897471611

8.3.3 - Determine the variance of c.

In [90]:
c.std()**2

6.666666666666666

8.3.4 - Print out the shape of the array c

In [91]:
c.shape

(3, 3)

8.3.5 - Transpose c and print out transposed result.

In [93]:
print(c.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


8.3.6 - Get the dot product of the array c with c. 

In [94]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

8.3.7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [95]:
(c * c.T).sum()

261

8.3.8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [96]:
(c * c.T).prod()

131681894400

## Setup 4

In [97]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]


8.4.1 - Find the sine of all the numbers in d

In [98]:
d = np.array(d)

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

8.4.2 - Find the cosine of all the numbers in d

In [99]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

8.4.3 - Find the tangent of all the numbers in d

In [100]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

8.4.4 - Find all the negative numbers in d

In [101]:
d[d < 0]

array([-90, -30, -45, -45])

8.4.5 - Find all the positive numbers in d

In [102]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

8.4.6 - Return an array of only the unique numbers in d.

In [103]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

8.4.7 - Determine how many unique numbers there are in d.

In [105]:
len(np.unique(d))

np.unique(d).size

11

8.4.8 - Print out the shape of d.

In [106]:
d.shape

(3, 6)

8.4.9 - Transpose and then print out the shape of d.

In [107]:
d.T.shape

(6, 3)

8.4.10 - Reshape d into an array of 9 x 2

In [110]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])